// apps/demo-next/src/components/Dashboard.tsx
"use client";

import React from 'react';

export default function Dashboard() {
  return (
    <div data-visora-src="src/components/Dashboard.tsx:7" className="min-h-screen bg-gray-900 text-white flex flex-col items-center justify-center p-8">
      <header data-visora-src="src/components/Dashboard.tsx:8" className="mb-12 text-center">
        <h1 data-visora-src="src/components/Dashboard.tsx:9" className="text-5xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-emerald-400 mb-4">
          Next.js Visora Demo
        </h1>
        <p data-visora-src="src/components/Dashboard.tsx:12" className="text-xl text-gray-400 max-w-2xl mx-auto">
          Hover over these elements with Visora running. You should see the inspector outline them and identify the exact source file and component!
        </p>
      </header>
      
      <div data-visora-src="src/components/Dashboard.tsx:17" className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-5xl">
        <div data-visora-src="src/components/Dashboard.tsx:18" className="bg-gray-800 p-6 rounded-xl border border-gray-700 hover:border-blue-500 transition-colors shadow-lg cursor-pointer">
          <div className="h-12 w-12 bg-blue-500/20 rounded-lg flex items-center justify-center mb-4">
            <span className="text-2xl">⚡</span>
          </div>
          <h3 className="text-xl font-bold text-white mb-2">Instant Feedback</h3>
          <p className="text-gray-400">Visora connects directly to the React Fiber tree in Next.js.</p>
        </div>
        
        <div data-visora-src="src/components/Dashboard.tsx:26" className="bg-gray-800 p-6 rounded-xl border border-gray-700 hover:border-purple-500 transition-colors shadow-lg cursor-pointer">
          <div className="h-12 w-12 bg-purple-500/20 rounded-lg flex items-center justify-center mb-4">
            <span className="text-2xl">🧠</span>
          </div>
          <h3 className="text-xl font-bold text-white mb-2">AI Powered</h3>
          <p className="text-gray-400">Shift+Click to edit this component using the Visora AI Patcher.</p>
        </div>
        
        <div data-visora-src="src/components/Dashboard.tsx:34" className="bg-gray-800 p-6 rounded-xl border border-gray-700 hover:border-emerald-500 transition-colors shadow-lg cursor-pointer">
          <div className="h-12 w-12 bg-emerald-500/20 rounded-lg flex items-center justify-center mb-4">
            <span className="text-2xl">🚀</span>
          </div>
          <h3 className="text-xl font-bold text-white mb-2">Universal Extraction</h3>
          <p className="text-gray-400">Works in App Router and Pages Router with zero configuration.</p>
        </div>
      </div>
      
      <footer data-visora-src="src/components/Dashboard.tsx:43" className="mt-16 text-gray-500 text-sm">
        <p>Built for the Visora V2 Multi-Framework Engine.</p>
      </footer>
    </div>
  );
}

// apps/demo-vue/src/components/Dashboard.vue
<script setup lang="ts">
// Vue Dashboard Component
</script>

<template>
  <div class="dashboard-container">
    <header class="header">
      <h1 class="title">
        Vue 3 Visora Demo
      </h1>
      <p class="subtitle">
        Hover over these elements with Visora running. You should see the inspector outline them and identify the exact source file and component!
      </p>
    </header>
    
    <div class="grid">
      <div class="card">
        <div class="icon-wrapper blue">
          <span class="icon">⚡</span>
        </div>
        <h3 class="card-title">Instant Feedback</h3>
        <p class="card-text">Visora connects directly to the Vue 3 component tree.</p>
      </div>
      
      <div class="card">
        <div class="icon-wrapper purple">
          <span class="icon">🧠</span>
        </div>
        <h3 class="card-title">AI Powered</h3>
        <p class="card-text">Shift+Click to edit this component using the Visora AI Patcher.</p>
      </div>
      
      <div class="card">
        <div class="icon-wrapper green">
          <span class="icon">🚀</span>
        </div>
        <h3 class="card-title">Universal Extraction</h3>
        <p class="card-text">Works natively in Vue 3 development mode with zero AST parsing.</p>
      </div>
    </div>
    
    <footer class="footer">
      <p>Built for the Visora V2 Multi-Framework Engine.</p>
    </footer>
  </div>
</template>

<style scoped>
.dashboard-container {
  min-height: 100vh;
  background-color: #111827;
  color: white;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  font-family: system-ui, -apple-system, sans-serif;
}

.header {
  margin-bottom: 3rem;
  text-align: center;
}

.title {
  font-size: 3rem;
  font-weight: 800;
  background: linear-gradient(to right, #42d392, #647eff);
  -webkit-background-clip: text;
  color: transparent;
  margin-bottom: 1rem;
}

.subtitle {
  font-size: 1.25rem;
  color: #9ca3af;
  max-width: 42rem;
  margin: 0 auto;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.5rem;
  width: 100%;
  max-width: 64rem;
}

.card {
  background-color: #1f2937;
  padding: 1.5rem;
  border-radius: 0.75rem;
  border: 1px solid #374151;
  transition: all 0.2s;
  cursor: pointer;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}

.card:hover {
  border-color: #42d392;
  transform: translateY(-2px);
}

.icon-wrapper {
  height: 3rem;
  width: 3rem;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1rem;
}

.icon-wrapper.blue { background-color: rgba(59, 130, 246, 0.2); }
.icon-wrapper.purple { background-color: rgba(168, 85, 247, 0.2); }
.icon-wrapper.green { background-color: rgba(16, 185, 129, 0.2); }

.icon { font-size: 1.5rem; }

.card-title {
  font-size: 1.25rem;
  font-weight: 700;
  margin-bottom: 0.5rem;
  color: white;
}

.card-text {
  color: #9ca3af;
  line-height: 1.5;
}

.footer {
  margin-top: 4rem;
  color: #6b7280;
  font-size: 0.875rem;
}
</style>
